### ISSUE TITLE
Where is the "randomness" from?

### ISSUE THREAD

**Issue by sutongkui** [zhan-xu/RigNet#41]
1, In the section of Quick Start, you mentioned  due to randomness, the results might be slightly different among each run. I'm wondering where is the "randomness" from? made by dropout?(i think dropout should only be applied in the training part).

2, Another is about the vertices number of input models, I have tested a model about 10k vertices, seems work well. If there is a model with several hundread thousands vertices,  can we use the model directly(don't consider the hardware limit,  memory and time)? I know that  you simplify it to 1k-5k firstly and then use some ohter techniques(such as nearest neighbour) to get the high-resolution result. 

Thanks.

**Comment by zhan-xu** [comment]
1. The randomness comes from two places as I can see. First is geodesic edges are sampled within a geodesic ball around each vertex (Line 87 of quick_start.py). The surface geodesic distance is further based on dense point sampling on the surface (Line 83 of quick_start.py).  The second randomness comes from BoneNet and RootNet as there are small pointnet++ to encode the joints, where the SAModule (Line 83 in models/PairCls_GCN.py) has random sub-sampling. I assume the first one is more important.

2. Not considering the hardware limitation, you can use the model directly, but still need to tune the parameters (threshold and bandwidth) since the density distribution are different. I don't think it will gain much improvement since joint clustering convert most steps into sparse joint space, except for the skinning part. BTW maybe in your test it works well because in the code, I downsample the mesh before skinning (Line 229-236 in quick_start.py)
