### ISSUE TITLE
ModelResource_RigNetv1_preproccessed/train/1095_v.txt not found.

### ISSUE THREAD

**Issue by pshn111** [zhan-xu/RigNet#45]
Hello, dear Zhan-Xu,

I'm trying to run Skinning prediction with this command python -u run_skinning.py --train_folder='ModelResource_RigNetv1_preproccessed/train/' --val_folder='ModelResource_RigNetv1_preproccessed/val/' --test_folder='ModelResource_RigNetv1_preproccessed/test/' --checkpoint='checkpoints/skinnet' --logdir='logs/skinnet' --train_batch=4 --test_batch=4 --lr=1e-4 --Dg --Lf

However, I got an error that is "OSError: ModelResource_RigNetv1_preproccessed/train/raw/ModelResource_RigNetv1_preproccessed/train/1095_v.txt not found."
I'm sure that the file 1095_v.txt exist at /ModelResource_RigNetv1_preproccessed/train/
Can you please provide some suggestions?

Thanks

**Comment by zhan-xu** [comment]
This is perhaps because the latest pytorch-geometric changes its way of organizing data. Now seems you need a folder called raw and another one called processed. You can check the latest organizing way and maybe create a "raw" folder for the data. Or maybe use a previous version of pytorch-geometric.
