### ISSUE TITLE
Is it possible to process A-pose mesh

### ISSUE THREAD

**Issue by CrossLee1** [zhan-xu/RigNet#47]
Thanks for your provided code.
I got some environment problem and havenot successfully run it to get the result.
I see your input mesh are all in T-pose, is it possible to process other posed mesh, like A-pose？Whats the result.

**Comment by CrossLee1** [comment]
Thanks for your relpy.
Two more questions:
1/ I see the predicted joints usually have duplicate ones, such as root, root_dup_0, root_dup_1, why?
2/ can we use the SMPL skeleton structure as input, and use the network to predict the joints location and skinning weights.

**Comment by zhan-xu** [comment]
1. This is for the skinning weights prediction when a joint has multiple children joints. Mesh surface is bind to "bones" instead of "joints". If one joint has three children, these three bones can control up to three parts of the mesh. By duplicate joints, I split joints with common parent to different bones. Each duplicated parent joint represents a bone.

2. This is not supported right now. We are aware that people are interested in fixed skeleton and will work on this later.

**Comment by tshrjn** [comment]
Is there Now a way to use RigNet with SMPL?

**Comment by zhan-xu** [comment]
Hi @tshrjn, how do you want to use RigNet with SMPL? SMPL has its own joint regressor and skinning. They also have SMPLX if you want more details.

**Comment by tshrjn** [comment]
I wanted to understand if we could use RigNet to rig a 3D humanoid like asset in a SMPL skeleton and skinning weights?
