### ISSUE TITLE
Cannot install the dependencies for the virtual environment

### ISSUE THREAD

**Issue by Danscap** [zhan-xu/RigNet#6]
I am using Windows 10 and running conda.

![image](https://user-images.githubusercontent.com/34867523/88484868-f5af0a00-cf3f-11ea-95cd-f3f6da0f6eac.png)

The first dependency did not work because there was a missing '=' so instead of open3d=0.9.0, it's supposed to be open3d==0.9.0.

The second dependency line cannot find those versions of torch and torchvision.

When I went through the link to try to find them myself, it's not clear which version I should get.

Please advise!

______________________________________________________________________________________________________________________________________
**Edit:** 

if necessary I can switch to any linux or previous windows environments to try to make this work.

If anyone has a working setup, I would love to know.

**Comment by zhan-xu** [comment]
Hi, I think this is because you are using windows. I checked the website and indeed there is not corresponding version there for windows. I suggest maybe switch to Linux if you can. If you prefer windows, I think you can install pytorch and pytroch_geometric with compatible versions to your CUDA and CUDNN. I think there won't be much difference.

**Comment by Danscap** [comment]
I kept going with windows, and I believe I have solved the dependencies issues (maybe, as I have more another issue further in the code that I will create a open a new issue for).


I downloaded the latest version of most of the dependencies, as required for pytorch v1.5.x
I will mark this as closed.
