### ISSUE TITLE
What does the data.skin_input represent?

### ISSUE THREAD

**Issue by Nisekoixmy** [zhan-xu/RigNet#67]
Hi Zhan Xu,

Thanks for providing this impressive work! May I know what is the data.skin_input represents? 
From what I understood, I think it is composed by (1/geodesic_distance). Is that correct? Could you please explain it a little more?

Best regards,
Nisekoi.

**Comment by zhan-xu** [comment]
Hi Nisekoi,
data.skin_input loads *_skin.txt [here](https://github.com/zhan-xu/RigNet/blob/master/datasets/skin_dataset.py#L97). The *_skin.txt files are generated [here](https://github.com/zhan-xu/RigNet/blob/master/gen_dataset.py#L112).

Specifically, suppose we consider K nearest bones and V vertices, skin_input has shape V*8K. Each bone-vertex pair has 8-d input, including start position (3-d), end position (3-d) of the bone, 1/geodesic_distance (1-d) and whether this bone is a "virtual bone" (1-d. "Virtual bone" is created for each leaf joint since we want the leaf joints to have skinning weights as well.)

**Comment by Nisekoixmy** [comment]
> Hi Nisekoi, data.skin_input loads *_skin.txt [here](https://github.com/zhan-xu/RigNet/blob/master/datasets/skin_dataset.py#L97). The *_skin.txt files are generated [here](https://github.com/zhan-xu/RigNet/blob/master/gen_dataset.py#L112).
> 
> Specifically, suppose we consider K nearest bones and V vertices, skin_input has shape V*8K. Each bone-vertex pair has 8-d input, including start position (3-d), end position (3-d) of the bone, 1/geodesic_distance (1-d) and whether this bone is a "virtual bone" (1-d. "Virtual bone" is created for each leaf joint since we want the leaf joints to have skinning weights as well.)

Thank you！After diving into your cide, i got the idea of it. But thank you for the quick reply.
I have another question which is related to the drop out of edges. I read your paper and found that when training the skinnet, you mentioned about dropping out edges. However, after investigation, i can't find it. May i ask you to point it out for me.？I'm really interested in your work and want to build some knowledge in this field. Thank you again.

**Comment by zhan-xu** [comment]
Edge dropout is implemented off-line. When generating geodesic edges [here](https://github.com/zhan-xu/RigNet/blob/master/gen_dataset.py#L37), we randomly choose a subset from the range.

**Comment by Nisekoixmy** [comment]
> 

Thank you! I will close this issue. It is clear to me now.
