### ISSUE TITLE
why remesh the model?

### ISSUE THREAD

**Issue by mooooona** [zhan-xu/RigNet#7]
I noticed that the preprocessed data you released has a remesh obj version, which is used to calculate geodesics and other places. I want to know why remesh is needed and how to get it?

thranks

**Comment by zhan-xu** [comment]
Hi. The main reason is that most networks in our method are graph neural networks, which means all the vertices are involved in the training as graph nodes. With large number of vertices, the training will become very slow. By remeshing, we constrain the vertices number between 1K and 5K. This also facilitates the networks adaptive to different resolution. (To adapt the networks to any resolution, a naive solution is to train them with data with various resolution. Since the data is limited, here we only focus on a specific range.)

To remesh the models, I suppose any mesh decimation and subdivision methods should work. For me, I used barycentric_subdivision from libigl for subdivision, and "edge quadric collapse decimation" from meshlab for decimation.

**Comment by mooooona** [comment]
thanks for your answer.
